definitions/dfe_analytics_dataform.js, definitions/joinGeoData.sqlx, definitions/spokeStatusView.sqlx
As well as changing status to state, I have updated and added 2 view to allow for better visulation
=> Dataform dfe qts analytics

definitions/joinGeoData.sqlx
Updated this script to include the country reference data
=> updated GeoData to include country reference

definitions/Applications_CustomQuery.sqlx, definitions/FI_Declines_CustomQuery.sqlx, definitions/spokeStatusView.sqlx
The dashboard was getting quite slow and this was because of using GDS custom queries. So moved it all into dataform
=> created new custom queries

definitions/Applications_Version_CustomQuery.sqlx, definitions/Eligibility_Version_CustomQuery.sqlx, definitions/FI_Declines_CustomQuery.sqlx, definitions/dfe_analytics_dataform.js
- added the new decline table without PII
- amended the decline/FI view to reflect the new table
- added a cleaned up application and eligibility version tables to enable user tracking
=> Updated and added new tables

definitions/assertions/zendesk_support_data_not_fresh.sqlx
Created an assertion to let us know if support ticket data is not being sent to BigQuery within 2 days
=> Added support ticket assertion

definitions/assessor_workload_per_day.sqlx
Created a new file to create daily averages of assessments completing and in progress per day.
=> New custom query for Looker Studio

definitions/declarations/ticket_fields.sqlx, definitions/zendesk/support_ticket_details.sqlx
Enhanced support_ticket_details table for AfQTS
=> support_ticket_details improvements

definitions/Requests_Custom_Query.sqlx
Adding _waiting to verify_ for professional standing
Rounding all _waiting_to_ outputs
=> Adding waiting to verify and roundings of outouts

package-lock.json, package.json
dfe-analytics-dataform upgrade to 1.5.1 and then 1.60.
=> dfe-analytics-dataform upgrade to 1.60

package-lock.json, package.json
=> Updated dfe-analytics-dataform package to v1.7.0

package-lock.json, package.json
=> def-analytics-dataform upgrade 1.7.1

definitions/FI_Declines_CustomQuery.sqlx
remove application_state field as no longer used and replaced by stage field
=> remove application_state, no longer used and replaced by stage

definitions/dfe_analytics_dataform.js
Hi Thomas, Adding descriptions you provided to BigQuery tables. Particularly useful now Jen is also on the team.
=> Added descriptions to email_reminders table.

definitions/Daily_Metrics.sqlx
Slight challenge was that issue_type is a repeated string, so had to unnest so that i could perform the LIKE function.
=> Updated Daily_metrics to include support tickets from BAT International / Teaching in England

definitions/dfe_analytics_dataform.js
- This will fail today as the field was added in the middle of yesterday, so some new entities will and won't have the new field
=> Added location_note to qualification_requests

definitions/dfe_analytics_dataform.js
Reverts DFE-Digital/apply-for-qualified-teacher-status-dataform#115
=> Revert "Added location_note to qualification_requests"

definitions/FI_Declines_CustomQuery.sqlx, definitions/dfe_analytics_dataform.js
[Add preliminary field to FI_Declines_CustomQuery](https://github.com/DFE-Digital/apply-for-qualified-teacher-status-dataform/commit/bfebc4bd55ea4f76ea77364ef5ede120ba75269c)
=> Add preliminary field to FI_Declines_CustomQuery

definitions/publications/2024_tra_annual_report_20230201_to_20230331.sqlx, definitions/publications/2024_tra_annual_report_20230401_to_20240331.sqlx
=> Updates to publication tables

definitions/operations/delete_inactive_datasets.sqlx
Adapted BAT delete_inactive_dataset code for AfQTS
=> Added delete_inactive_dataset

definitions/dfe_analytics_dataform.js
To be merged in once https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/2528 is merged in.
=> [AQTS-688] Renaming the dqt_match column to be trs_match

definitions/publications/2025_tra_annual_report_20230201_to_20230331.sqlx, definitions/publications/2025_tra_annual_report_20230401_to_20240331.sqlx, definitions/publications/2025_tra_annual_report_20240401_to_20250331.sqlx
No PR requested at this stage as these queries will undergo QA as part of the publication process.
=> Ensured Zimbabwe applications are excluded from all queries.

definitions/dfe_analytics_dataform.js
Following the merge of https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/2709 - We are adding new columns to the `further_information_request_items` table
=> Add new columns for further_information_request_items table

definitions/dfe_analytics_dataform.js
New columns relating to new prioritisation work: https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/2781
This to be merged once the PR above has been merged in
=> Adding new columns relating to new prioritisation journey for applicants
